### ISSUE TITLE
Benchmark results for `Mooncake`

### ISSUE THREAD

**Issue by yebai** [nsiccha/StanBlocks.jl#1]
Thanks for the nice work! 

Is it possible to include the benchmarking results for `Mooncake` too? It is not yet performance-optimal, but @willtebbutt is working on it.

**Comment by nsiccha** [comment]
Now that I see it like that, maybe I have to interpolate `e.mooncake!`? I'll check out whether that makes a difference tomorrow, but the results are roughly in line with what I had observed before, and the non-interpolated version seems to work well for all the other benchmarks as far as I can tell.

**Comment by willtebbutt** [comment]
Okay. I think what you're doing it fine. I've done some performance profiling locally and, at least on the first example, there's some really weird performance issues. I'm not entirely sure what's going on yet, but I suspect it's going to involve a fix on Mooncake's end. Will keep you apprised.

**Comment by nsiccha** [comment]
Great! The fact that it's possible to get 0 allocations both for plain Julia, enzyme and mooncake using that approach also indicates to me that it's fine the way I do it. Will close this issue then, feel free to open another issue if I should change or update+rerun things.
